window.__DEFAULT_EDIT_COPY__ = {
  "copy-001": "AI",
  "copy-002": "如何变革",
  "copy-003": "视觉表达",
  "copy-004": "产品体验",
  "copy-005": "01",
  "copy-006": "PROMPT：抽象到具象",
  "copy-007": "生图关键词拆解",
  "copy-008": "02",
  "copy-009": "工作流到 SKILL",
  "copy-010": "从视觉侧的实际案例探究 AI 如何提效",
  "copy-011": "03",
  "copy-012": "统一碎片化视频流程",
  "copy-013": "重构 AI 视频产出",
  "copy-014": "04",
  "copy-015": "AI 动效落地变革",
  "copy-016": "AI 动效提效与协作，AI牛逼动效如何落地",
  "copy-017": "01",
  "copy-018": "<span class=\"title-accent\">抽象到具象</span>",
  "copy-019": "生图流程拆解<div>Prompt构成</div>",
  "copy-020": "工具在变，<span class=\"title-accent\">工作方式</span>也在变",
  "copy-021": "单独生图",
  "copy-022": "从单点视觉生成开始。",
  "copy-023": "视频生成",
  "copy-024": "静态画面扩展到时间和镜头。",
  "copy-025": "复杂任务",
  "copy-026": "Codex、Claude 开始处理代码、工具和完整任务。",
  "copy-027": "以前：自己完成一个设计任务",
  "copy-028": "现在：先拆解任务，再调用不同 AI",
  "copy-029": "从设计师到 <span class=\"title-accent\">AI 统筹者</span>",
  "copy-030": "设计师",
  "copy-031": "重点执行需求交付结果",
  "copy-032": "AI<br>统筹者",
  "copy-033": "Codex / Claude",
  "copy-034": "代码、工具搭建与实现",
  "copy-035": "GPT Image",
  "copy-036": "专业生图与视觉探索",
  "copy-037": "豆包",
  "copy-038": "思考、整理与快速尝试",
  "copy-039": "即梦",
  "copy-040": "快速生图与视频",
  "copy-041": "Kimi",
  "copy-042": "辅助研究与长内容",
  "copy-043": "<b>先拆任务</b>明确目标和环节",
  "copy-044": "<b>统筹需要做到</b>掌握AI能力并合理调用",
  "copy-045": "让不同 AI 围绕同一个目标协作。提供有效加成",
  "copy-046": "<span class=\"title-accent\">Prompt</span>：把抽象感觉变成具象描述",
  "copy-047": "高级一点",
  "copy-048": "更有氛围",
  "copy-049": "再有感觉一些",
  "copy-050": "继续追问",
  "copy-051": "继续拆解",
  "copy-052": "<b>色调</b>是什么颜色关系更高级？",
  "copy-053": "<b>光线</b>什么样的光更有氛围？",
  "copy-054": "<b>镜头</b>什么视角更有冲击力？",
  "copy-055": "<b>角色</b>主体的什么动作更贴合品牌？",
  "copy-056": "把问题反馈进行细致的拆解",
  "copy-057": "一张图可以拆成<span class=\"title-accent\">哪些部分</span>",
  "copy-058": "拆解画面",
  "copy-059": "主体",
  "copy-060": "通过动作、表情<br>来表达品牌信息",
  "copy-061": "辅助物体",
  "copy-062": "补充信息与活跃画面",
  "copy-063": "环境场景",
  "copy-064": "前景、中景、背景<br>强化空间关系、质感<br>",
  "copy-065": "氛围渲染",
  "copy-066": "天气、色调、光影<br>情感化表达<br>",
  "copy-067": "镜头/透视/构图",
  "copy-068": "俯视、仰视、倾斜<br>画面冲击力<br>",
  "copy-069": "文案排版",
  "copy-070": "位置、字体、排版<br>表达产品信息<br>",
  "copy-071": "参考图不是复制，而是<span class=\"title-accent\">主动拆解</span>",
  "copy-072": "我喜欢的是构图，还是色彩？",
  "copy-073": "光影是什么样的？",
  "copy-074": "镜头是什么？",
  "copy-075": "氛围是什么？",
  "copy-076": "哪些元素是我真正想要的？",
  "copy-077": "哪些只是参考图本身的内容？",
  "copy-078": "视觉拆解 <i>→</i> 重新组织 <i>→</i> 更可控的结果",
  "copy-079": "万能参考图<span class=\"title-accent\">prompt</span>",
  "copy-080": "VISUAL SKILL",
  "copy-081": "",
  "copy-082": "打开链接 ↗",
  "copy-083": "<code>{\n  <span class=\"code-key\">\"image_prompt\"</span>: \"以 json 格式描述这幅图，描述准确复刻原始图像所需的所有方面，包括主体、视角构图、风格、光线、图片比例、有关物品、服装、发型、复杂细节、配饰、摄影器材、环境、身体姿势以及任何其他相关元素的具体信息，确保能够精确地重现原始图像的每一个细节。\",\n  <span class=\"code-key\">\"output\"</span>: \"要求输出 json 格式提示词，字数 750 字以内。\",\n  <span class=\"code-key\">\"video_prompt\"</span>: \"同时以 json 格式给这幅图定制一个适配的视频提示词。\"\n}</code>",
  "copy-084": "02",
  "copy-085": "<span class=\"title-accent\">工作流到 SKILL</span>",
  "copy-086": "从视觉侧探究 AI 如何提效",
  "copy-087": "宠物险<span class=\"title-accent\">节气海报</span>",
  "copy-088": "情人节",
  "copy-089": "春分",
  "copy-090": "清明",
  "copy-091": "劳动节",
  "copy-092": "立夏",
  "copy-093": "端午节",
  "copy-094": "父亲节",
  "copy-095": "小暑",
  "copy-096": "企微推送，从元旦开始到现在，持续产出 30+ 张",
  "copy-097": "工作流之前，先有<span class=\"title-accent\">品牌基础</span>",
  "copy-098": "先搭建品牌规范，包括Logo、IP、字体、品牌色、营销设计规范等等，为后续 Prompt模版、工作流和 Skill的搭建提供稳定品牌基础",
  "copy-099": "立夏<span class=\"title-accent\">Prompt 模板案例</span>",
  "copy-100": "IP母版、画面参考",
  "copy-101": "方便 AI 参照比例、特点以及风格。",
  "copy-102": "IP动作描述",
  "copy-103": "动作、表情、服装、前后关系。",
  "copy-104": "前景与背景",
  "copy-105": "前景：左上角、右下角、虚化、构图；背景：明确场景内容。",
  "copy-106": "氛围与辅助角色",
  "copy-107": "光、雨、雪、叶子、花瓣、光粒、灰尘、光斑、风；燕子、鸟、蝴蝶、蜜蜂，让视觉重心从 IP 拉到整体节气主题。",
  "copy-108": "视角、色调与强化词",
  "copy-109": "俯视、仰视、侧面、特写、从某处俯视或仰视、大透视；颜色、曝光、暗调、冷暖、夕阳、照在脸上的阳光；有冲击力、艺术大师、动态模糊。",
  "copy-110": "标题文案",
  "copy-111": "结合节气文化与品牌亲和感；水、冰、雪、花、草、叶子等材质让标题真正融入画面。",
  "copy-112": "<span class=\"title-accent\">从Prompt模板到完整AI工作流</span>",
  "copy-113": "节气信息 群通知<br>信息对齐&nbsp;",
  "copy-114": "提醒系统",
  "copy-115": "前期信息搜集",
  "copy-116": "AI调研",
  "copy-117": "运营需求 画面",
  "copy-118": "文案",
  "copy-119": "构思画面表现",
  "copy-120": "创意",
  "copy-121": "prompt模版",
  "copy-122": "即梦生图",
  "copy-123": "主观调整",
  "copy-124": "合成",
  "copy-125": "让AI参与到项目的每一个节点，包括前期提醒、视觉调研、信息对齐后的创意设计、再到真正生图阶段、以及合成后的AI辅助细节调整。<div><span style=\"color: rgba(255, 255, 255, 0.58); font-size: 15px; text-align: right;\">把可以规范化和自动化的环节连接起来，从整体</span>提升效率和质量。</div>",
  "copy-126": "<span style=\"color: rgba(255, 255, 255, 0.55); font-size: 16px; text-align: center;\">实际作用：</span><div><span style=\"color: rgba(255, 255, 255, 0.55); font-size: 16px; text-align: center;\">· 规范建立，品牌信息表达更稳定</span></div><div><span style=\"color: rgba(255, 255, 255, 0.55); font-size: 16px; text-align: center;\">· 准确结合节日节气文化和产品调性</span></div><div><span style=\"color: rgba(255, 255, 255, 0.55); font-size: 16px; text-align: center;\">· 规范化产出流程，降低协作成本</span></div>",
  "copy-127": "工作流到<span class=\"title-accent\">一键生成 Skill</span>",
  "copy-128": "SKILL",
  "copy-129": "工作流内容直接转换",
  "copy-130": "历史海报资源作为参考",
  "copy-131": "规则：主体、场景、构图、氛围、字体、尺寸等",
  "copy-132": "创意",
  "copy-133": "禁止项",
  "copy-134": "标题字体规范",
  "copy-135": "Python 合成",
  "copy-136": "让已经确定的视觉规则和经验，可以被 AI 重复调用。",
  "copy-137": "Skill 问题1：<span class=\"title-accent\">创意不可控</span>",
  "copy-138": "主体动作奇怪",
  "copy-139": "生成不稳定",
  "copy-140": "氛围与节日不匹配",
  "copy-141": "与业务关系弱",
  "copy-142": "画面完整但创意不成立",
  "copy-143": "品牌规范容易写成规则，但创意是抽象的，需要继续保留人的判断。",
  "copy-144": "限定创意范围， <span class=\"title-accent\">AI 直接调用 </span>",
  "copy-145": "节气氛围",
  "copy-146": "色调范围",
  "copy-147": "IP 动作",
  "copy-148": "业务关系",
  "copy-149": "10 组",
  "copy-150": "表情与场景",
  "copy-151": "创意预设*5<br>减少出错",
  "copy-152": "<b>AI更多时候是规则执行者</b><div><b>而创意想法、抽象感受的表达和判断是设计师重要的价值体现</b></div>",
  "copy-153": "问题2：<span class=\"title-accent\">标题文字难以融入</span>",
  "copy-154": "和画面一起生成",
  "copy-155": "<br>",
  "copy-156": "Python合成画面和文字",
  "copy-157": "先完成视觉画面",
  "copy-158": "文字单独生成",
  "copy-159": "AI Python 合成",
  "copy-160": "<span class=\"gold-accent\">让AI一次解决所有问题通常不够稳定。</span>把任务合理拆分，AI给到的结果可能更好。",
  "copy-161": "生成案例",
  "copy-162": "“用节气海报的 Skill，帮我做一张白露海报，",
  "copy-163": "要求露水与 IP 结合。”",
  "copy-164": "人的初始想法",
  "copy-165": "Skill 调用规则",
  "copy-166": "AI 继续生成",
  "copy-167": "其他适合<span class=\"title-accent\">Skill 化</span>的工作",
  "copy-168": "视觉创意前期思维发散",
  "copy-169": "快速整理创意方向，抓取对应图片参考，生成一份带图片的思维导图。",
  "copy-170": "查看 Skill ↗",
  "copy-171": "宠物头图skill",
  "copy-172": "从猫狗品种、表情、动作、氛围等，规范化宠物险生态产品的头图生成",
  "copy-173": "查看 Skill ↗",
  "copy-174": "03",
  "copy-175": "<span class=\"title-accent\">统一碎片化流程</span>",
  "copy-176": "重构 AI 视频产出",
  "copy-177": "亚宠展发布会 · <span class=\"title-accent\">视频流程</span>",
  "copy-178": "从大纲到脚本",
  "copy-179": "先把完整内容和目标整理清楚。",
  "copy-180": "详细分镜头脚本",
  "copy-181": "AI 处理后，再由人工修改和优化。",
  "copy-182": "基础设定",
  "copy-183": "人物、宠物、场景和品牌信息。",
  "copy-184": "58 张分镜画面",
  "copy-185": "AI 生成后，逐张人工检查和优化。",
  "copy-186": "视频生成",
  "copy-187": "prompt重点表达镜头语言、品牌、“动”",
  "copy-188": "旁白与 BGM",
  "copy-189": "声音继续围绕同一个内容目标。",
  "copy-190": "统一剪辑",
  "copy-191": "把全部内容连接为完整视频。",
  "copy-192": "AI 先处理",
  "copy-193": "人脑持续检查与优化",
  "copy-194": "保证内容、品牌和场景准确",
  "copy-195": "生成视频前，先检查<span class=\"title-accent\">58 张分镜</span>",
  "copy-196": "01",
  "copy-197": "06",
  "copy-198": "11",
  "copy-199": "16",
  "copy-200": "21",
  "copy-201": "26",
  "copy-202": "31",
  "copy-203": "36",
  "copy-204": "41",
  "copy-205": "46",
  "copy-206": "52",
  "copy-207": "58",
  "copy-208": "需要人脑校验",
  "copy-209": "<b data-edit-id=\"copy-210\">内容</b>是否准确表达脚本？",
  "copy-210": "内容",
  "copy-211": "<b data-edit-id=\"copy-212\">品牌</b>是否符合品牌调性？",
  "copy-212": "品牌",
  "copy-213": "<b data-edit-id=\"copy-214\">场景</b>是否符合发布会环境？",
  "copy-214": "场景",
  "copy-215": "<b data-edit-id=\"copy-216\">处理</b>不满意的画面先重新生成。",
  "copy-216": "处理",
  "copy-217": "58 张分镜画面全部确认以后，才真正开始生成视频。",
  "copy-218": "视频 Prompt 更关注<span class=\"title-accent\">时间与镜头</span>",
  "copy-219": "VIDEO<br>PROMPT",
  "copy-220": "人物怎么动？运动方向是什么？",
  "copy-221": "画面前后如何变化？",
  "copy-222": "镜头怎么动、怎么转场、景别怎么变？",
  "copy-223": "AI 结合脚本、分镜画面与基础设定，为每个镜头生成对应的视频 Prompt。",
  "copy-224": "AI 把碎片化流程<span class=\"title-accent\">连接起来</span>",
  "copy-225": "完整信息先统一：脚本、人物、场景、品牌调性与视觉方向。",
  "copy-226": "后续内容基于已有信息，有目的地继续产出。",
  "copy-227": "脚本",
  "copy-228": "分镜",
  "copy-229": "人物设定",
  "copy-230": "场景设定",
  "copy-231": "画面",
  "copy-232": "视频",
  "copy-233": "配乐",
  "copy-234": "剪辑",
  "copy-235": "AI<br>统筹",
  "copy-236": "<span>已有信息统一 → 有目的地产出 → 持续人工优化 → 完整视频</span><em>更加统一 · 更加协调 · 效率更高 · 更贴近业务目标</em>",
  "copy-237": "04",
  "copy-238": "<span class=\"title-accent\">AI 落地变革</span>",
  "copy-239": "AI 动效提效与协作",
  "copy-240": "AI 前后，<span class=\"title-accent\">动效创作与认知</span>都在变化",
  "copy-241": "效果创作 · 以前",
  "copy-242": "AE 手工抠帧",
  "copy-243": "效果依赖工具熟练度、动效知识和个人经验。",
  "copy-244": "效果创作 · 现在",
  "copy-245": "AI 协助创作",
  "copy-246": "AI 寻找实现方式，并辅助生成和调整。",
  "copy-247": "知识范围 · 以前",
  "copy-248": "设计师个人认知",
  "copy-249": "能力边界取决于自己接触过什么、记得什么。",
  "copy-250": "知识范围 · 现在",
  "copy-251": "AI 网络动效知识库",
  "copy-252": "连接更广的案例、技术方案和交付经验。",
  "copy-253": "<span class=\"title-accent\">Lottie</span> 的制作变革",
  "copy-254": "适合产品矢量动效",
  "copy-255": "按钮、图标、状态动画等。",
  "copy-256": "以前",
  "copy-257": "导出设计图层，在 AE 中重新制作，再通过插件导出。",
  "copy-258": "现在",
  "copy-259": "Figma Motion AI 直接基于设计稿制作、调整并导出 Lottie，让设计稿、动效与交付尽量在同一个平台完成。",
  "copy-260": "Figma 设计稿",
  "copy-261": "Motion AI",
  "copy-262": "制作与调整",
  "copy-263": "导出 Lottie",
  "copy-264": "<span class=\"title-accent\">精灵图</span>：承接 AI 动效落地",
  "copy-265": "为什么需要精灵图",
  "copy-266": "Lottie 对部分渐变、遮罩、复杂效果和低端机型兼容存在限制；复杂营销动画需要另一种交付方式。",
  "copy-267": "过去的流程",
  "copy-268": "AI 视频 / MP4 → AE 剪辑 → 抠图 → PNG 序列 → 精灵图合成 → 压缩 → 调试。",
  "copy-269": "一键导出精灵图工具",
  "copy-270": "导入 AI 视频，在网页里完成简单剪辑、尺寸调整、帧率调整、精灵图生成、压缩和导出。",
  "copy-271": "把重复操作集中到一个网页工具里，明显提升实际动效交付效率。",
  "copy-272": "把踩过的坑变成<span class=\"title-accent\">动效规则库</span>",
  "copy-273": "规则从哪里来",
  "copy-274": "个人经验、历史项目和聊天记录中反复出现的问题。",
  "copy-275": "沉淀什么内容",
  "copy-276": "精灵图尺寸限制、帧率问题、Lottie 渐变 Bug、低端机型兼容，以及性能和交付问题。",
  "copy-277": "让 AI 帮助查询，把个人经验变成团队可以复用的知识。",
  "copy-278": "把视觉语言整理成<span class=\"title-accent\">网页动效 Skill</span>",
  "copy-279": "VISUAL",
  "copy-280": "RUNNING<br>EXPERIENCE",
  "copy-281": "WEB MOTION SKILL",
  "copy-282": "从描述效果到直接体验效果",
  "copy-283": "我把喜欢的视觉语言、动效方式和交互经验整理成一套 Skill。它适合宠物、活动和营销类项目，可以快速生成能够直接运行、继续调整的网页动效。",
  "copy-284": "这份分享中的网页动效也来自这套 Skill，欢迎大家直接尝试。",
  "copy-285": "AI 释放的，不只是<span class=\"title-accent\">执行效率</span>",
  "copy-286": "找资料",
  "copy-287": "整理信息",
  "copy-288": "生图",
  "copy-289": "视频生成",
  "copy-290": "动效制作",
  "copy-291": "交付",
  "copy-292": "规则查询",
  "copy-293": "找资料",
  "copy-294": "整理信息",
  "copy-295": "生图",
  "copy-296": "视频生成",
  "copy-297": "动效制作",
  "copy-298": "交付",
  "copy-299": "规则查询",
  "copy-300": "不只是以后可以做更多图",
  "copy-301": "而是把时间放回前期创意、业务理解、用户体验和产品表达",
  "copy-302": "自己的工作内核，也从单纯完成视觉，慢慢向更完整的体验设计延伸。",
  "copy-303": "当设计、产品和技术共享更多工作流、工具与规则，协作也会更高效、更有意思。",
  "copy-304": "THANKS",
  "copy-305": "<span class=\"final-row\"><em data-edit-id=\"copy-306\">期待AI</em><strong data-edit-id=\"copy-307\">在我们之后的工作中，</strong></span><span class=\"final-row final-row-after\"><em data-edit-id=\"copy-308\">带来更多</em><strong data-edit-id=\"copy-309\">新的发展和变革</strong></span>",
  "copy-306": "期待AI",
  "copy-307": "在我们之后的工作中，",
  "copy-308": "带来更多",
  "copy-309": "新的发展和变革",
  "copy-310": "期待",
  "copy-311": "AI",
  "copy-312": "发展",
  "copy-313": "变革",
  "copy-314": "<br>",
  "copy-315": "发展",
  "copy-316": "变革",
  "copy-317": "<br>"
};
